### ISSUE TITLE
tracking: proof checking

### ISSUE THREAD

**Issue by c-cube** [sneeuwballen/zipperposition#58]
Summarize progress in proof checking:

  * [x] update proof generation with renamings (or not), including rewrite
    steps and demod steps
  * [x] test this (without checking) on all TPTP; look for quick errors; merge into dev
  * ~~[ ] write `LLTerm.t` and basic functions (substitution/typing in particular)~~
  * [x] write simple CC based tableau (if possible, somehow incremental)
  * [x] conversion statement → formula
  * [x] make inference steps sth like
        `intros [x,y,z]; apply C1 [g(y),x+1]; apply C2[z,z]; tableau`
  * [x] skip some steps based on metadata (esa/arith) **for now**
  * [x] final summary on how many steps skipped/ok/fail
  * [x] debug on pure FO
  * [ ] store result of checking inside proof steps
  * [x] direct β reduction of llterms
      ~~ite/bool/β reduction rules in tableau~~
  * [ ] make rewriting under `λ` terms pass proof checking
  * [ ] proof checking for arith: FM / omega(?)/cooper
  * [ ] proof check CNF steps (see 
  * [ ] lazy equality exchange (case split on all equalities between arith terms?)
  * [ ] proof checking for full HO (#52)
  * [ ] turn checking on by default
  * [ ] fast proof checker (#53)
